import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "../components/CartContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="navbar bg-base-100 shadow-sm">
          <div className="navbar-start">
            <a className="btn btn-ghost text-xl">Ratanak Skin Care</a>
          </div>
          <div className="navbar-center hidden lg:flex">
            <ul className="menu menu-horizontal px-1">
              <li><a href="/menutable">Menu</a></li>
              <li><a href="/">Order</a></li>
              <li><a href="/orderpage">History Order</a></li>
            </ul>
          </div>
        </div>
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
